### ISSUE TITLE
Running bash scripts in command line

### ISSUE THREAD

**Issue by GangstersPairOfDice** [pwncollege/welcome-dojo#4]
Bash scripts cannot ( afaik ? ) be run by just calling the name of it?

Fx. trying to run `solve` by itself, throws an error.

![image](https://github.com/pwncollege/welcome-dojo/assets/89167407/7b51c96f-da42-4470-a698-43afc58a5b84)

Can fix this by prompting the user, to type in the correct command, which afaik, is `./solve`

https://github.com/pwncollege/welcome-dojo/blob/e8fd630083c0aa8514679460c2904839f21989ea/welcome/vscode/solve#L45C79-L45C81

**Comment by GangstersPairOfDice** [comment]
If y'all are feeling lazy, I can write up a PR?

**Comment by zardus** [comment]
Ahh, of course `$0` isn't great to use there. Could you PR this to change it to something like `$(realpath $0)` instead?

**Comment by miningape** [comment]
@GangstersPairOfDice +1 for PR
